### ISSUE TITLE
securing minio access key and secret key with Hashicorp vault

### ISSUE THREAD

**Issue by akshayuppal3** [minio/charts#109]
I referred to this link https://gist.github.com/harshavardhana/427f6cffc068418278129f4e65cbf9cc to inject secrets via vault sidecar injection. But instead of using deployment file I am updating the values.yaml and deploying via helm. 
So to export access key and secret key as environment variables we need to source the secrets and entrypoint script but for that, we need to issue a bash command similar to https://gist.github.com/harshavardhana/427f6cffc068418278129f4e65cbf9cc#file-vault-secrets-minio-yaml-L48 but can we do the same with values.yaml. 
I see we have extraArgs in values yaml but I guess it appends the argument instead of being entry-point script. Can we add command with values yaml?

my code so far
```
values.yaml
 .............. trimming some lines
  podAnnotations:
    vault.hashicorp.com/agent-pre-populate: "false"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-minio-access-key: "kv/data/shared/blob/name"
    vault.hashicorp.com/agent-inject-secret-minio-secret-key: "kv/data/shared/blob/key"
    vault.hashicorp.com/role: "minio-app"
    vault.hashicorp.com/agent-inject-template-minio-access-key: |
      {{`
      {{- with secret "some path" -}}
          export MINIO_ACCESS_KEY="{{ .Data.data.access_key }}"
      {{- end -}}
      `}}
    vault.hashicorp.com/agent-inject-template-minio-secret-key: |
      {{`
      {{- with secret "some path" -}}
          export MINIO_SECRET_KEY="{{ .Data.data.secret_key }}"
      {{- end -}}
      `}}

  # sourcing vault secrets as mentioned here: https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example
  command: [
      "/bin/sh",
      "-ce",
      "source /vault/secrets/minio-secret-key && /vault/secrets/minio-access-key
      && /usr/bin/docker-entrypoint.sh"]
```

**Comment by harshavardhana** [comment]
No more feature requests are allowed with this helm chart, please refer to our https://github.com/minio/operator

**Comment by akshayuppal3** [comment]
I guess I should have framed it better, I am not looking for a feature request .. it is more of a question. How can I inject minio secrets with vault side car injection? I am not asking for any feature. Appreciate your quick reply
