### ISSUE TITLE
Deprecation of MinIO Chart without suitable replacement for MinIO Gateway

### ISSUE THREAD

**Issue by djsly** [minio/charts#114]
What is the expectation from a user's point of view if that chart is used to deploy minIO as a gateway ? 

The operator won't be supporting the gateway feature, so there won't be a way to deploy the gateway moving forward.

**Comment by harshavardhana** [comment]
Yes even the gateway is getting removed from the server https://github.com/minio/minio/pull/11938 moving to https://github.com/minio/ming soon. 

You are free to fork this project and use it on your own.

**Comment by djsly** [comment]
so I'm guessing https://github.com/minio/ming will have its own chart ?

**Comment by harshavardhana** [comment]
> so I'm guessing https://github.com/minio/ming will have its own chart ?

ming may have its own chart eventually @djsly
