### ISSUE TITLE
Accessing via Kubernetes service name fails

### ISSUE THREAD

**Issue by pjoshi751** [minio/charts#13]
I have deployed minio using helm charts in standalone mode.  My application running as a pod on the Kubernetes cluster is able to access minio with `http://<minio pod ip>:9000`  but not with `http://<service name>:9000/`.    The service name is `minio` that is connected to pod endpoint.  Any settings that need to be changed to make the pod accessible via service?

**Comment by loftkun** [comment]
Here is an example that works fine.
If your appplication accesses minio service from other namespace, try to use "`{service-name}.{namaspace}.svc.cluster.local`" domain.

```sh
# deploy minio
$ helm install test stable/minio

# check
$ kubectl get po -o wide
NAME                          READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
test-minio-7b95b5d7f7-rbdnc   1/1     Running   0          24m   172.17.0.4   minikube   <none>           <none>
$ kubectl get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP          55d
test-minio   NodePort    10.96.189.91   <none>        9000:31466/TCP   24m
$

# access to minio pod from same namespace
$ kubectl run -it --rm --restart=Never curl-pod --image=curlimages/curl -- sh -c "curl 'http://172.17.0.4:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
<title>MinIO Browser</title>
pod "curl-pod" deleted
$

# access to minio service from same namespace
$ kubectl run -it --rm --restart=Never curl-pod --image=curlimages/curl -- sh -c "curl 'http://test-minio:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
<title>MinIO Browser</title>
pod "curl-pod" deleted
$

# create other namespace
$ kubectl create namespace other

# access to minio pod from other namespace
$ kubectl run -it --rm --restart=Never curl-pod -n other --image=curlimages/curl -- sh -c "curl 'http://172.17.0.4:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
<title>MinIO Browser</title>
pod "curl-pod" deleted
$

# access to minio service from other namespace
# use "{service-name}.{namaspace}.svc.cluster.local" domain. 
$ kubectl run -it --rm --restart=Never curl-pod -n other --image=curlimages/curl -- sh -c "curl 'http://test-minio.default.svc.cluster.local:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
<title>MinIO Browser</title>
pod "curl-pod" deleted
$
```

**Comment by harshavardhana** [comment]
> Here is an example that works fine.
> If your application accesses minio service from other namespace, try to use "`{service-name}.{namaspace}.svc.cluster.local`" domain.
> 
> ```shell
> # deploy minio
> $ helm repo add minio https://helm.min.io/
> $ helm install test minio/minio
> 
> # check
> $ kubectl get po -o wide
> NAME                          READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
> test-minio-7b95b5d7f7-rbdnc   1/1     Running   0          24m   172.17.0.4   minikube   <none>           <none>
> $ kubectl get svc
> NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
> kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP          55d
> test-minio   ClusterIP   10.96.189.91   <none>        9000:31466/TCP   24m
> $
> 
> # access to minio pod from same namespace
> $ kubectl run -it --rm --restart=Never curl-pod --image=curlimages/curl -- sh -c "curl 'http://172.17.0.4:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
> <title>MinIO Browser</title>
> pod "curl-pod" deleted
> $
> 
> # access to minio service from same namespace
> $ kubectl run -it --rm --restart=Never curl-pod --image=curlimages/curl -- sh -c "curl 'http://test-minio:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
> <title>MinIO Browser</title>
> pod "curl-pod" deleted
> $
> 
> # create other namespace
> $ kubectl create namespace other
> 
> # access to minio pod from other namespace
> $ kubectl run -it --rm --restart=Never curl-pod -n other --image=curlimages/curl -- sh -c "curl 'http://172.17.0.4:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
> <title>MinIO Browser</title>
> pod "curl-pod" deleted
> $
> 
> # access to minio service from other namespace
> # use "{service-name}.{namaspace}.svc.cluster.local" domain. 
> $ kubectl run -it --rm --restart=Never curl-pod -n other --image=curlimages/curl -- sh -c "curl 'http://test-minio.default.svc.cluster.local:9000/minio/login' -H 'User-Agent: Mozilla' | grep title"
> <title>MinIO Browser</title>
> pod "curl-pod" deleted
> $
> ```

Closing this as explained by @loftkun

**Comment by pjoshi751** [comment]
The browser works for me too, but looks like API calls are failing.  Can you check with store and retrieve also work for you without giving the IP?
