### ISSUE TITLE
Allow to provide trusted 3rd party certificates as secrets 

### ISSUE THREAD

**Issue by tacrocha** [minio/charts#15]
Greetings! I was trying to integrate minio with a keycloak which uses a self-signed certificate, but the current chart doesn't have a mechanism to provide trusted certificates to be mounted in the `CAs/` directory. Using the chart, the only way to mount any certificate in that folder requires also to enable `tls` for the minio cluster, which is not something I needed for mine. 

Could you please allow users to pass in the values.yaml a list of secrets that they want to be mounted inside the `CAs` directory, regardless of other `tls` configurations? Thanks.

**Comment by harshavardhana** [comment]
Good idea, feel free to send a fix @tacrocha

**Comment by nitisht** [comment]
Fixed by #20
