### ISSUE TITLE
Unable to update chart to v7.0.0

### ISSUE THREAD

**Issue by rxbn** [minio/charts#21]
I cannot upgrade the helm chart to version 7.0.0 because the readinessProbe values were deleted but they still remain in the deployment template. This results in a nil pointer exception: `at <.Values.readinessProbe.initialDelaySeconds>: nil pointer evaluating interface {}.initialDelaySeconds"`

**Comment by harshavardhana** [comment]
Will remove them..

**Comment by rxbn** [comment]
@harshavardhana thank you :)
