### ISSUE TITLE
The helm default installation will not run

### ISSUE THREAD

**Issue by huaxk** [minio/charts#24]
I use helm3 to install minio on k8s.
`helm install minio minio/minio`
the command is finished, but minio pod is not running for the following reasons in pod log:
```
ERROR Unable to initialize backend: Unable to write to the backend
> Please ensure MinIO binary has write permissions for the backend
HINT:
Use 'sudo chown -R <your-username> /export && sudo chmod u+rxw /export' to provide sufficient permissions.
```
What's wrong?

**Comment by bclermont** [comment]
@huaxk it need an `initContainer` that do that

**Comment by bclermont** [comment]
I create a PR that fix this

**Comment by bclermont** [comment]
just tried that PR and my pod start now

**Comment by harshavardhana** [comment]
> ERROR Unable to initialize backend: Unable to write to the backend
> > Please ensure MinIO binary has write permissions for the backend
> HINT:
> Use 'sudo chown -R <your-username> /export && sudo chmod u+rxw /export' to provide sufficient permissions.

changing permissions is unexpected - so change the securityContext to match your disk permissions.

**Comment by madianas** [comment]
@harshavardhana there is an initContainer enabled by  `persistence.volumePermissions.enabled` setting for standalone mode, why can't there be for distributed mode?
