### ISSUE TITLE
Please include README.md file when packaging minio chart

### ISSUE THREAD

**Issue by mjschmidt** [minio/charts#3]
This is greatly helpful when you want to helm fetch, easy to include and will allow the documentation to manifest in things like Rancher and Openshift.

**Comment by harshavardhana** [comment]
Fixed in 6.0.3

**Comment by mjschmidt** [comment]
You rock thanks man!
![image](https://user-images.githubusercontent.com/6544930/89811363-90951000-db0c-11ea-8990-a485aa57cabe.png)
