### ISSUE TITLE
Some questions about how to use this helm chart

### ISSUE THREAD

**Issue by wzf1943** [minio/charts#39]
Hi, I'm newbie of minio. Write now I'm using helm to deploy minio on our gke cluster. I have some question about minio helm chart. And I cannot find out answer on your official website. So I don't know if you guys could help me. 

1. How to scale cluster up (add more nodes or more drive into cluster)? Can I just change replica number and upgrade chart? The key thing here is I want to keep my old data.

2. How to set reduce mode in helm chart? I found set this environment variable MINIO_STORAGE_CLASS_RRS: "EC:2" I'm not sure if this is right, cause I didn't see any performance difference after I set this mode.

**Comment by harshavardhana** [comment]
If you need all these features you should use https://github.com/minio/operator - helm chart is not going to support these features.
