### ISSUE TITLE
Breaking Change with Scheme

### ISSUE THREAD

**Issue by rcanderson23** [minio/charts#42]
Latest update to helm charts changed logic for Liveness probe in the deployment. `scheme` is set to `http` or `https` depending on TLS settings. This value is used for port name and scheme in Liveness probe, however only `HTTP` or `HTTPS` are allowed values for the scheme value in the probe.

Error logs from Argo CD after today's update:
```
Deployment.apps "minio" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet.scheme: Unsupported value: "http": supported values: "HTTP", "HTTPS"
```

**Comment by harshavardhana** [comment]
Fixed in 8.0.0, the liveness probe is removed.
