### ISSUE TITLE
Chart 7.2.2 has invalid schema values

### ISSUE THREAD

**Issue by chris-sanders** [minio/charts#46]
Introduced in the 7.2.2 chart as a change to the schema and the values are invalid, they need to be capitalized. This was fine in 7.2.1, just needs a rename for 7.2.2 and a new release.

Deployment.apps "minio" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet.scheme: Unsupported value: "http": supported values: "HTTP", "HTTPS"

**Comment by harshavardhana** [comment]
Upgrade to 8.0.0 we removed Liveness checks.
