### ISSUE TITLE
Persistence.Enabled is not considered for Standalone mode

### ISSUE THREAD

**Issue by deshetti** [minio/charts#54]
I am installing the minio helm chart v8.0.0. I notice that the `persistence.enabled: true` is only being considered for `mode: distributed`. When setting `mode: standalone`, the PVC is being deleted when the chart is uninstalled. Is this the expected behavior?

We have an application that we are using minio for, where I would like to run minio only on standalone mode since it is not very heavy in usage, yet want to have the ability for the volume to not be deleted if anyone accidentally uninstalls minio using the helm chart.

**Comment by deshetti** [comment]
@harshavardhana does it mean that `standalone` by design doesn't care if `persistence.enabled: true` based on your comment https://github.com/minio/charts/issues/61#issuecomment-724961829

**Comment by harshavardhana** [comment]
> @harshavardhana does it mean that `standalone` by design doesn't care if `persistence.enabled: true` based on your comment [#61 (comment)](https://github.com/minio/charts/issues/61#issuecomment-724961829)

yes it doesn't @deshetti

**Comment by deshetti** [comment]
@harshavardhana thanks.
