### ISSUE TITLE
Support for KMS 

### ISSUE THREAD

**Issue by jamie-34254** [minio/charts#59]
When using a KMS you might want to set KMSVaultCAPath to a filepath to a secret, but this chart doesn't currently allow you to mount a custom secret for Vault's TLS CA

**Comment by harshavardhana** [comment]
You should use minio/operator @jamie-34254 - charts are in code freeze and not taking anymore feature requests.

**Comment by jamie-34254** [comment]
thanks!

**Comment by fdlk** [comment]
This was actually already implemented in #20, I think.
