### ISSUE TITLE
StatefulSet version issue

### ISSUE THREAD

**Issue by cts-zeero** [minio/charts#64]
I am unable to deploy into a 1.16.X cluster due to this api version regression rollback.
https://github.com/minio/charts/commit/32090f4d0014bab621a808bdb763fdec56ee8f40#diff-f58a5a53cbc35bc7f8a9740b0b3579428e3638092a2f222fdb25c18bae5de4f2

I am getting this error:

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"`

**Comment by harshavardhana** [comment]
> 32090f4#diff-f58a5a53cbc35bc7f8a9740b0b3579428e3638092a2f222fdb25c18bae5de4f2

That PR is needed because of other issues @cts-zeero - can you dump what your `helm template` actually prints?

**Comment by harshavardhana** [comment]
> > [32090f4](https://github.com/minio/charts/commit/32090f4d0014bab621a808bdb763fdec56ee8f40)#diff-f58a5a53cbc35bc7f8a9740b0b3579428e3638092a2f222fdb25c18bae5de4f2
> 
> That PR is needed because of other issues @cts-zeero - can you dump what your `helm template` actually prints?

Closing as stale issue.
