### ISSUE TITLE
Switch to using chart-releaser to release charts to repository

### ISSUE THREAD

**Issue by paulczar** [minio/charts#7]
Currently it appears that you're using the master branch to house the packaged charts (.tgz) files and the index.yml for the repository/gh-pages.

We recommend using the chart-releaser github action that will actually use the github releases feature to host the charts and the gh-pages branch to hose the index.yaml.  This keeps the repository clean of binary files as well as automates the release process.

see https://github.com/helm/chart-releaser-action

**Comment by harshavardhana** [comment]
The current process serves our purposes, as we wish to manually sign the releases eventually. 

Those private keys cannot be passed onto GitHub.

**Comment by harshavardhana** [comment]
> The current process serves our purposes, as we wish to manually sign the releases eventually.
> 
> Those private keys cannot be passed onto GitHub.

Closing as not necessary
