### ISSUE TITLE
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)

### ISSUE THREAD

**Issue by nengbai** [minio/charts#76]
Today I deployment minio-8.0.5 with mode=distributed on Glusterfs storage, still error :Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
1. First to helm install
helm install --namespace clpsbase --set mode=distributed --set persistence.size=5Gi --generate-name minio/minio
2. check pod status
helm -n clpsbase list |grep minio
minio-1606637076	clpsbase 	1       	2020-11-29 16:04:40.398505525 +0800 CST	deployed	minio-8.0.5        	master     

 kubectl -n clpsbase get pod |grep minio-
minio-1606637076-0                   1/1     Running     0          11m
minio-1606637076-1                   1/1     Running     0          11m
minio-1606637076-2                   1/1     Running     0          11m
minio-1606637076-3                   1/1     Running     0          11m
[root@k8s-node8 minio]# 
3. check pod logs and got  error "Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)"
kubectl -n clpsbase logs -f minio-1606637076-0

Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)

**Comment by harshavardhana** [comment]
> Today I deployment minio-8.0.5 with mode=distributed on Glusterfs storage, still error :Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to encrypt config Storage resources are insufficient for the read operation.)

GlusterFS does not support O_DIRECT by default please use real persistent disks with MinIO not another NAS

**Comment by nengbai** [comment]
Thanks you fallback so quickly. Could I use local storage to deploy distributed  minio ?  like as below
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: export-minio-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: export-minio-0
    namespace: clpsbase
  local:
    path: /miniodata/pvc-minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 11.110.114.14
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-0
  namespace: clpsbase
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: export-minio-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: export-minio-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: export-minio-1
    namespace: clpsbase
  local:
    path: /miniodata/pvc-minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 11.110.114.15
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-1
  namespace: clpsbase
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: export-minio-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: export-minio-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: export-minio-2
    namespace: clpsbase
  local:
    path: /miniodata/pvc-minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 11.110.114.16
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-2
  namespace: clpsbase
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: export-minio-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: export-minio-3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: export-minio-3
    namespace: clpsbase
  local:
    path: /miniodata/pvc-minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 11.110.114.17
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-3
  namespace: clpsbase
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: export-minio-3

**Comment by nengbai** [comment]
I have 9 nodes with 3 master and 6 work nodes, the master nodes with taints . I try deploy minion with mode distrution , still got error: Warning  FailedScheduling  <unknown>  default-scheduler  0/9 nodes are available: 3 node(s) had taints that the pod didn't tolerate, 6 node(s) had volume node affinity conflict. How to fix minio on  local-stoarage node ?

1. create pv and pvc with local-stoarage
kubectl -n clpsbase get pvc |grep export
export-minio-0                                Bound    export-minio-0                             30Gi       RWO            local-storage   28m
export-minio-1                                Bound    export-minio-1                             30Gi       RWO            local-storage   28m
export-minio-2                                Bound    export-minio-2                             30Gi       RWO            local-storage   28m
export-minio-3                                Bound    export-minio-3                             30Gi       RWO            local-storage   28m
2. local-storage 
 kubectl get sc
NAME                  PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
glusterfs (default)   kubernetes.io/glusterfs        Delete          Immediate              false                  29h
local-storage         kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  25h

3.kubectl -n clpsbase get pod |grep minio
minio-0                  0/1     Pending   0          10m
minio-1                  0/1     Pending   0          10m
minio-2                  0/1     Pending   0          10m
minio-3                  0/1     Pending   0          10m

4. Got Error:
kubectl -n clpsbase describe pod minio-0
Name:           minio-0
Namespace:      clpsbase
Priority:       0
Node:           <none>
Labels:         app=minio
                controller-revision-hash=minio-5c5b47b488
                release=minio
                statefulset.kubernetes.io/pod-name=minio-0
Annotations:    checksum/config: 0b10b81a6d896d16d2b2aa0808c4de805e3aabd4a6d07b9a2bb2b526d5ced6c2
                checksum/secrets: b560b16eda801a87193f7010c45311ee5351695f02404ff74685718549960ce5
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/minio
Containers:
  minio:
    Image:      minio/minio:RELEASE.2020-11-19T23-48-16Z
    Port:       9000/TCP
    Host Port:  0/TCP
    Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server  http://minio-{0...3}.minio-svc.clpsbase.svc.cluster.local/export
    Requests:
      memory:  4Gi
    Environment:
      MINIO_ACCESS_KEY:  <set to the key 'accesskey' in secret 'minio'>  Optional: false
      MINIO_SECRET_KEY:  <set to the key 'secretkey' in secret 'minio'>  Optional: false
    Mounts:
      /export from export (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from minio-token-j7m9t (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  export:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  export-minio-0
    ReadOnly:   false
  minio-user:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  minio
    Optional:    false
  minio-token-j7m9t:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  minio-token-j7m9t
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/9 nodes are available: 3 node(s) had taints that the pod didn't tolerate, 6 node(s) had volume node affinity conflict.
