### ISSUE TITLE
Missing comments in shipped Helm Chart

### ISSUE THREAD

**Issue by dp-42** [minio/charts#78]
Hello,

as the Helm chart best practices highly encourages, you have commented your values file accordingly, so that users are guided through the configuration options. That is great!
See here: https://github.com/minio/charts/blob/master/minio/values.yaml

However, there seems to be an issue with released charts as they do not ship any comments.
As an example, just look into the latest chart release: https://github.com/minio/charts/blob/master/releases/minio-8.0.5.tgz
It seems there is an issue with the packaging process so that all comments get lost...

Could you please have a look?
Many thanks!

**Comment by harshavardhana** [comment]
helm packaging removes all the comments always and no way to preserve them, this is why we comment them for documentation purposes.

**Comment by dp-42** [comment]
Hi @harshavardhana 

thank you for the fast reply.

Helm package does not remove comments! There was an issue in Helm a year ago that caused the deletion of the comments (see https://github.com/helm/helm/issues/6951). This problem was solved a long time ago...

When I package the Chart myself, the comments are preserved:
```
➜ helm package minio -d releases/
walk.go:74: found symbolic link in path: /mnt/code/charts/minio/README.md resolves to /mnt/code/charts/README.md
Successfully packaged chart and saved it to: releases/minio-8.0.7.tgz

➜ helm inspect values releases/minio-8.0.7.tgz
## Provide a name in place of minio for `app:` labels
##
nameOverride: ""
...

➜ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Please ensure that you use a somewhat recent version of the `helm` binary.
Many thanks!
