### ISSUE TITLE
 To use tls secret instead generic secret for Ingress 

### ISSUE THREAD

**Issue by jgato** [minio/charts#8]
Would be possible to configure the ingress with a secret tls, instead of a secret generic with cert and key files? Most of Helm Charts we are using make use of this feature to configure the ingress.

**Comment by harshavardhana** [comment]
Sure, feel free to send a PR

**Comment by jgato** [comment]
Digg in into it, I realize that is working ok. I was confused with the tls and the ingress section. TLS section is for the certificate for internal usage (generic secret), the Ingress section needs a secret tls for the external access.
