### ISSUE TITLE
Versioning not supported on latest Helm chart/Docker image

### ISSUE THREAD

**Issue by DanielJonesEB** [minio/charts#83]
For some reason I'm not able to enable versioning on a bucket, despite using the latest version of the Helm chart - 8.0.7, which uses the image `minio/minio:RELEASE.2020-12-03T05-49-24Z`.

It was my understanding that versioning had been added as a feature a long time ago? However, when I try enabling versioning on a bucket, I get the following:

```
$ mc version enable myminio/release-candidates
mc: <ERROR> Unable to enable versioning. A header you provided implies functionality that is not implemented.
```

I'm using version `RELEASE.2020-11-17T00-39-14Z` of the client.

**Comment by harshavardhana** [comment]
Versioning is not supported if you are deploying a single drive mode. You need to use erasure coding. https://github.com/minio/minio/tree/master/docs/bucket/versioning#concepts 

> Versioning feature is only available in erasure coded and distributed erasure coded setups.
