### ISSUE TITLE
Long Minio pod start with volume with many files on it

### ISSUE THREAD

**Issue by ValeriiVozniuk** [minio/charts#88]
Hi,

I've faced an issue with Minio pod being in ContainerCreating state for 30+ minutes after resizing the pvc for it. 120 GB volume was full, and I've added additional 30GB to it. Upon checking the kubelet log I saw a lot of following messages
```Dec 15 09:30:53 server47 docker[29162]: W1215 09:30:53.996821   30951 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/a6e52d23-563c-4d2d-875d-ec87502b2240/volumes/kubernetes.io~secret/reportportal-minio-token-ghwth and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699```
Upon checking the link above I've found that delay was caused by kubernetes running chmod on each file on the volume due to fsGroup attribute is set on pod. Unfortunately, there is not much progress in that bug, so it would be nice to have this issue fixed on minio chart side.
As runAsUser/runAsGroup are already present in spec, I think fsGroup can be removed, and instead a simple init container with not recursive chmod on volume can be used if needed

**Comment by harshavardhana** [comment]
> Dec 15 09:30:53 server47 docker[29162]: W1215 09:30:53.996821 30951 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/a6e52d23-563c-4d2d-875d-ec87502b2240/volumes/kubernetes.io~secret/reportportal-minio-token-ghwth and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699

This is k8s CSI doing things automatically we do not do this ourselves and this chart or MinIO not responsible for this.
